### ISSUE TITLE
Feature: Add support for multi-line text

### ISSUE THREAD

**Issue by ewwink** [dylanatsmith/betterplaceholder#8]
it is supported?

**Comment by dylanatsmith** [comment]
Not currently but it could be added.

1. Replace the text input with a textarea
2. Replace the [JS on line 71](https://github.com/dylanatsmith/betterplaceholder/blob/3e698cfa5b6ec91d010a79de48b5d8a11b799a86/js/main.js#L71) to…
  a. Separate each line
  b. Strip each line of leading and trailing whitespace
  c. Strip empty lines?
  c. Concatenate each line separated by `%0A` (URL encoded character for newline)
  d. Add the resulting string to the URL

**Comment by ewwink** [comment]
OK thanks
